### ISSUE TITLE
Selection Changed Event 

### ISSUE THREAD

**Issue by DavidBarishev** [quicoli/WPF-AutoComplete-TextBox#2]
Would it be possible to implement a selection changed event that will fire when the user changes selection or writes text which is equal to one of the keys ? It would be great.

**Comment by quicoli** [comment]
Hi David,

I would like to understand how would you use that,  so I can figure out how
to implement it for you...

Thanks
Em 08/05/2016 16:34, "David Barishev" <notifications@github.com> escreveu:

**Comment by DavidBarishev** [comment]
@quicoli  Yes i can explain.
Basicly i have a text box representing some kind of a comparison between two selected items from two different controls ,first one is a list view and the other one is the wpf autocomplete text box , now i want when the selection changes of the user in the autocomplete text box , it will fire up the event , so i can update the textbox with the new given parameter . 
This isn't possible to do with a binding (I think) ,  as the textbox relies on a compare function that receives two items , one from each control , and return a int value. Therefore i have an object bound to the textbox , with a difference property and the two compared objects  , and when one of them gets updated  , the difference get update as well .
I did implement this in the list view , as it already supports selection changed.
Hope this describes my use , cheers .

**Comment by DavidBarishev** [comment]
Also , I think it's worth mentioning , if a bind a textbox to the selected item , it will display the selected item and switch when the user selects a different item , basically  , I except the selection changed behavior , like the binding.

**Comment by quicoli** [comment]
David,

I believe what you need can be accomplished using MVVM...

Take a look on this code:

<wpf:AutoCompleteTextBox VerticalAlignment="Top" Height="25" Grid.Row="0"
Grid.Column="1" DisplayMember="FullName"
ItemTemplateSelector="{StaticResource CustomTemplateSelector}"
Watermark="Search here" IconPlacement="Left" IconVisibility="Visible"
Provider="{StaticResource ResourceKey=FileSystemSuggestionProvider}"
x:Name="Actb"> <wpf:AutoCompleteTextBox.SelectedItem> <Binding
Path="SelectedPath" Mode="TwoWay"> <Binding.ValidationRules>
<local:RequiredValidationRule/> </Binding.ValidationRules> </Binding>
</wpf:AutoCompleteTextBox.SelectedItem>
<wpf:AutoCompleteTextBox.LoadingContent> <TextBlock Text="Loading..."
Margin="5" FontSize="14" /> </wpf:AutoCompleteTextBox.LoadingContent>
<wpf:AutoCompleteTextBox.Icon> <Border Width="20" Height="20"> <Image
Source="Resources/search_icon.png" Height="16" Width="16"
HorizontalAlignment="Center" VerticalAlignment="Center" /> </Border>
</wpf:AutoCompleteTextBox.Icon> </wpf:AutoCompleteTextBox>

See we have a selected item binded.  So,  each time the user picks an item
up,  your property in your viewmodel is changing and can be used to
anything...
Em 08/05/2016 16:50, "David Barishev" <notifications@github.com> escreveu:

@quicoli <https://github.com/quicoli> Yes i can explain.
Basicly i have a text box representing some kind of a comparison between
two selected items from two different controls ,first one is a list view
and the other one is the wpf autocomplete text box , now i want when the
selection changes of the user in the autocomplete text box , it will fire
up the event , so i can update the textbox with the new given parameter .
This isn't possible to do with a binding (I think) , as the textbox relies
on a compare function that receives two items , one from each control , and
return a int value. Therefore i have an object bound to the textbox , with
a difference property and the two compared objects , and when one of them
gets updated , the difference get update as well .
I did implement this in the list view , as it already supports selection
changed.
Hope this describes my use , cheers .

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/quicoli/WPF-AutoComplete-TextBox/issues/2#issuecomment-217742208>

**Comment by DavidBarishev** [comment]
Yes that did the trick , you can close the question now.
I didn't now this was possible as im still learning wpf . 
Thanks for all the help.
