### ISSUE TITLE
Passing parameter to Provider

### ISSUE THREAD

**Issue by JD-Robbs** [quicoli/WPF-AutoComplete-TextBox#59]
Is it possible to somehow pass a parameter to the provider?

I'm looking for the ability to dynamically load the suggestions in the provider based on a passed parameter.

E.g. pseudo-XAML `<AutoCompleteTextBox Provider="CustomProvider" ListToUse="{Binding SourceListName}" />`.

And then in the provider using the passed string, say `string SourceListName = "CountryList"`, to return the list I want.

I can't hard-code it since my app allows the dynamic creation of autocomplete lists which I want users to be able to hook their TextBoxes up to.

**Comment by quicoli** [comment]
Hi

The provider can be used in a databind, so you could use  a converter and set your parameters

👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: JD-Robbs ***@***.***>
Sent: Monday, December 5, 2022 9:11:04 PM
To: quicoli/WPF-AutoComplete-TextBox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [quicoli/WPF-AutoComplete-TextBox] Passing parameter to Provider (Issue #59)


Is it possible to somehow pass a parameter to the provider?

I'm looking for the ability to dynamically load the suggestions in the provider based on a passed parameter.

E.g. pseudo-XAML <AutoCompleteTextBox Provider="CustomProvider" ListToUse="{Binding SourceListName}" />.

And then in the provider using the passed string, say string SourceListName = "CountryList", to return the list I want.

I can't hard-code it since my app allows the dynamic creation of autocomplete lists which I want users to be able to hook their TextBoxes up to.

**Comment by JD-Robbs** [comment]
My god, this is amazing. This did it. Thank you, Sir!
