### ISSUE TITLE
Auto complete failed implement ISuggestionProvider on .net framework version

### ISSUE THREAD

**Issue by bopin2020** [quicoli/WPF-AutoComplete-TextBox#61]
<editors:AutoCompleteTextBox
            Width="400"
            Height="26"
            Margin="20"
            HorizontalAlignment="Left"
            VerticalAlignment="Top"
            CharacterCasing="Upper"
            MaxLength="50"
            Provider="{StaticResource ResourceKey=NumbersProvider}"
            SelectedItem="{Binding SelectedNumber, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
            Watermark="Enter a number (issue #43)">
            <editors:AutoCompleteTextBox.LoadingContent>
                <TextBlock
                    Margin="5"
                    FontSize="14"
                    Text="Loading..." />
            </editors:AutoCompleteTextBox.LoadingContent>
        </editors:AutoCompleteTextBox>

When I click IEnumerate<string> range values or listbox value, textbox text was null which was not expection of me.
![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/49940777/0921c5da-8d82-438b-9721-1ac85a56a2dc)

**Comment by bopin2020** [comment]
BTY just .net framework environment

![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/49940777/8ce7fabe-659b-4f79-9050-913c4d49ea36)

**Comment by bopin2020** [comment]
For diving into inside,  BindingEvaluator.cs Evaluate method   SetBinding Value should failed that result in Vaule was null invariably
![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/49940777/d465c318-e02f-4d1c-9e61-be73d344d02d)

**Comment by quicoli** [comment]
Hi @bopin2020,

I updated the SimpleDemo to build using .NET Framework 4.8

![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/8388239/008aa467-37d7-40e8-8bfa-3c3d14d25aa8)

Ran it as .NET Framework 4.8

![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/8388239/aebc2769-bfdf-4d47-93fd-8b5ae27506ea)

But I didn't get any exception or errors. So far it is working as expected, the **TextBox is updated when you select an item**.
When you only move the mouse over an item it is not actually selected. However, if you navigate through item using keyboard arrow keys, it is selected. To me, that's the expected behavior and it is consistent in both .NET (framework and Core).

![yV9xjaPO1N](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/8388239/e589f7b6-df11-4e43-a47b-9ed29e7085d1)
