### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by ninhpham96** [quicoli/WPF-AutoComplete-TextBox#67]
how to create validation for AutoCompleteTextBox.

**Comment by quicoli** [comment]
Hi

What do you mean by validation?
Validation should be in your ViewModel.

👍


________________________________
From: ninhpham96 ***@***.***>
Sent: Thursday, October 26, 2023 3:28:54 AM
To: quicoli/WPF-AutoComplete-TextBox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [quicoli/WPF-AutoComplete-TextBox] Custom Validation (Issue #67)


how to create validation for AutoCompleteTextBox.

**Comment by ninhpham96** [comment]
![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/116655628/80603a60-7573-454e-82cf-a10d87228f37)
Sorry for the previous question being unclear.
I realized that, if the value being entered is outside of GetSuggestions then validation will not be checked to report an error.
When the value entered is outside GetSuggestions, this value cannot be binding to PropertyPath.
Sorry if my presentation is a bit confusing.

https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/116655628/f363c231-1d51-4d92-91fc-dcfbefc9d574

**Comment by quicoli** [comment]
Hi,

I think I got what you need...

@ninhpham96, you are applying the validation to the selected item. If what you have typed isn't in the list, there's no selected item. That's why validation isn't triggered.
You need to apply a validation to other property, bound to the typed text.
See this example.

![image](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/8388239/7ee0eced-73fb-48a6-acde-af3e7546a3d3)

The validation should be in the TypedFruit property, not in the SelectedFruit.

I hope this helps.

**Comment by ninhpham96** [comment]
wow, it worked well, it's really great, thank you so much.
